import z from "zod";
import { join } from "node:path";
import { applyPatch, parsePatch, undoPatch } from "../../patch/engine";
import { loadContract, saveContract } from "../../contract/store";
import { reviseContract } from "../../contract/types";
import { validateContractPreconditions } from "../../contract/preconditions";
import type { Tool } from "../types";

export const applyPatchTool: Tool<any, unknown> = {
  name: "apply_patch",
  description:
    "Validate, preview, and atomically apply multi-file unified patches. Use dryRun first for risky edits; stale context, conflicts, concurrent changes, symlink escapes, binary files, and malformed patches are rejected. Set mode=undo with a prior undoToken to restore verified agent-owned changes.",
  parameters: z
    .object({
      patch: z
        .string()
        .optional()
        .describe("unified diff or structured *** Update File patch"),
      dryRun: z.boolean().optional().default(false),
      includeDiff: z.boolean().optional().default(false),
      mode: z.enum(["apply", "undo"]).optional().default("apply"),
      undoToken: z.string().optional(),
      contractId: z.string().uuid().optional(),
    })
    .superRefine((value, ctx) => {
      if (value.mode === "apply" && !value.patch)
        ctx.addIssue({
          code: "custom",
          message: "patch is required in apply mode",
        });
      if (value.mode === "undo" && !value.undoToken)
        ctx.addIssue({
          code: "custom",
          message: "undoToken is required in undo mode",
        });
    }),
  getPermissionKey: (args: any) => ({
    capability: "modify",
    target: ".",
    explanation:
      args.mode === "undo"
        ? "Undo verified agent-owned patch changes in the workspace"
        : `${args.dryRun ? "Preview" : "Apply"} a multi-file patch in the workspace`,
    risk: "high",
  }),
  getPermissionKeys: (args: any) => {
    if (args.mode === "undo")
      return [
        {
          capability: "modify",
          target: ".",
          explanation:
            "Undo verified agent-owned patch changes in the workspace",
          risk: "high",
        },
      ];
    return parsePatch(args.patch).map((file) => ({
      capability: "modify" as const,
      target: file.path,
      explanation: `${args.dryRun ? "Preview" : "Apply"} patch changes to ${file.path}`,
      risk: "high" as const,
    }));
  },
  execute: async (args: any, signal, context) => {
    const workspaceRoot = context?.workspace?.authorizedRoot ?? process.cwd();
    if (args.mode === "undo") return undoPatch(args.undoToken, signal);
    let contract;
    const contractDirectory = join(workspaceRoot, ".chiku", "contracts");
    if (args.contractId) {
      contract = await loadContract(
        args.contractId,
        undefined,
        contractDirectory,
      );
      if (!contract)
        throw new Error(`change contract not found: ${args.contractId}`);
      const checks = await validateContractPreconditions(
        contract,
        workspaceRoot,
      );
      const failed = checks.filter((check) => !check.passed);
      if (failed.length)
        throw new Error(
          `change contract preconditions failed: ${failed.map((check) => check.kind).join(", ")}`,
        );
      if (args.patch !== contract.proposedPatch)
        throw new Error("patch does not match the persisted change contract");
    }
    const result = await applyPatch(workspaceRoot, args.patch, {
      dryRun: args.dryRun,
      signal,
    });
    if (contract && result.undoToken) {
      await saveContract(
        reviseContract(contract, {
          status: "executing",
          rollback: {
            strategy: "patch-undo-token",
            undoToken: result.undoToken,
            notes: "Undo token generated by the controlled patch executor.",
          },
          evidenceReferences: [
            ...contract.evidenceReferences,
            ...result.files
              .filter((file) => file.changed)
              .map((file) => `applied:${file.path}`),
          ],
        }),
        contractDirectory,
      );
    }
    return {
      applied: result.applied,
      dryRun: result.dryRun,
      undoToken: result.undoToken,
      rolledBack: result.rolledBack,
      files: result.files.map((file) => ({
        path: file.path,
        changed: file.changed,
        originalHash: file.originalHash,
        ...(args.includeDiff ? { diff: file.diff } : {}),
      })),
    };
  },
};
